// Sugestões de bairro e cidade para o campo "Onde você vota?".
// Fonte: base territorial da Central Samuel (bairros ativos), em 14/09/2026.
// São só sugestões: a pessoa pode digitar qualquer bairro ou cidade.

export const CIDADES = [
  'Mauá', 'Santo André', 'São Bernardo do Campo', 'Ribeirão Pires',
  'Rio Grande da Serra', 'Diadema', 'São Caetano do Sul', 'Suzano', 'São Paulo'
];

export const BAIRROS = {
  'Mauá': ["Bairro da Matriz","Bandeirantes","Bocaina","Capuava","Centro","Chácara Braz","Chácara Maria Aparecida","Chácara Maria Francisca","Country Park","Fazenda Capitão João","Fazenda Oratório","Itapark Novo","Itapark Velho","Jardim Adelina","Jardim Agatti","Jardim Alto da Boa Vista","Jardim Anchieta","Jardim Aracy","Jardim Araguaia","Jardim Bela Vista","Jardim Bógus","Jardim Bom Recanto","Jardim Brasília","Jardim Camila","Jardim Campo Verde","Jardim Canadá","Jardim Cecília Tereza","Jardim Cerqueira Leite","Jardim Cinerama","Jardim Cleide","Jardim Coimbra","Jardim Colúmbia","Jardim Cruzeiro","Jardim Éden","Jardim Elizabete","Jardim Elvira","Jardim Esperança","Jardim Estrela","Jardim Feital","Jardim Flórida","Jardim Guapituba","Jardim Haydeé","Jardim Hélida","Jardim Idel","Jardim Ipê","Jardim Itapark","Jardim Itapeva","Jardim Itaussu","Jardim Kennedy","Jardim Luzitano","Jardim Maria Eneida","Jardim Maringá","Jardim Mauá","Jardim Miranda D'Aviz","Jardim Nóbrega","Jardim Olinda","Jardim Oratório","Jardim Paranavaí","Jardim Paulista","Jardim Pedroso","Jardim Pilar","Jardim Primavera","Jardim Quarto Centenário","Jardim Rosina","Jardim Rosinelli","Jardim Salgueiro","Jardim Santa Lídia","Jardim Santana","Jardim Santista","Jardim São Gabriel","Jardim São João","Jardim São Jorge","Jardim São Jorge do Guapituba","Jardim São Judas","Jardim São Luiz","Jardim São Miguel","Jardim São Sebastião","Jardim Silvia","Jardim Silvia Maria","Jardim Sônia Maria","Jardim Zaíra","Loteamento Industrial Coral","Núcleo Pedrinha","Parque Alvorada","Parque Boa Esperança","Parque das Américas","Parque das Orquídeas","Parque dos Bandeirantes","Parque Itrapoã","Parque Jaguari","Parque São Vicente","Recanto Vital Brasil","Sertãozinho","Sítio Bela Vista","Sítio Feital","Vila Alice","Vila Ana","Vila Aparecida","Vila Assis Brasil","Vila Augusto","Vila Batoni","Vila Carlina","Vila Cláudia","Vila Correia","Vila Dirce","Vila Falchi","Vila Fausto Neves Morelli","Vila Feital","Vila Gomes","Vila Guarani","Vila Independência","Vila João Ramalho","Vila Lisboa","Vila Magini","Vila Mercedes","Vila Moreli","Vila Noêmia","Vila Nossa Senhora das Vitórias","Vila Nossa Senhora de Aparecida","Vila Nossa Senhora de Fátima","Vila Nova Canaã","Vila Nova Mauá","Vila Otávio Miniguini","Vila Real","Vila Santa Rosa","Vila São Francisco","Vila São João","Vila São José","Vila São Roberto","Vila Sonia","Vila Tavares","Vila Verde","Vila Vitória","Zaira 4"],
  'Santo André': ["Campestre","Casa Branca","Centreville","Centro","Cidade São Jorge","Jardim Aclimação","Jardim Alvorada","Jardim Alzira Franco","Jardim Ana Maria","Jardim Bela Vista","Jardim Cipreste","Jardim Cristiane","Jardim das Maravilhas","Jardim do Estádio","Jardim Guarará","Jardim Ipanema","Jardim Las Vegas","Jardim Oratório","Jardim Paraíso","Jardim Progresso","Jardim Rina","Jardim Riviera","Jardim Santo Alberto","Jardim Santo André","Jardim Santo Antônio","Jardim Stella","Jardim Utinga","Paraíso","Parque Capuava","Parque das Nações","Parque Erasmo Assunção","Parque Gerassi","Parque Jaçatuba","Parque João Ramalho","Parque Marajoara","Parque Novo Oratório","Parque Oratório","Recreio da Borda do Campo","Santa Maria","Santa Terezinha","Silveira","Vila Alpina","Vila Alzira","Vila Apiaí","Vila Assunção","Vila Bela Vista","Vila Camilópolis","Vila Curuçá","Vila Floresta","Vila Francisco Matarazzo","Vila Gilda","Vila Guiomar","Vila Helena","Vila Humaitá","Vila João Ramalho","Vila Linda","Vila Lutécia","Vila Marina","Vila Mazzei","Vila Metalúrgica","Vila Palmares","Vila Pires","Vila Progresso","Vila Sacadura Cabral","Vila Santa Maria","Vila São Pedro","Vila Scarpelli","Vila Suíça","Vila Tibiriçá","Vila Valparaíso"],
  'São Bernardo do Campo': ["Assunção","Baeta Neves","Centro","Cooperativa","Demarchi","Ferrazópolis","Jardim do Lago","Montanhão","Nova Petrópolis","Parque Alvarenga","Paulicéia","Planalto","Rudge Ramos","Vila Euclides","Vila Ferrazópolis","Vila São José","Vila Vitória"],
  'Ribeirão Pires': ["Centro Alto","Colônia","Jardim Caçula","Jardim Santa Inês","Jardim Santa Luzia","Jardim Serrano","Núcleo Colonial","Parque Aliança","Santana","São Caetaninho","Suíssa","Vila Belmiro"],
  'Rio Grande da Serra': ["Parque América","Santa Tereza","Vila Figueiredo","Vila Lopes"],
  'Diadema': ["Canhema","Casa Grande","Eldorado","Jardim das Nações","Serraria","Taboão","Vila Canhema","Vila Nogueira","Vila Santa Rita"],
  'São Caetano do Sul': ["Barcelona","Centro","Fundação","Jardim São Caetano","Nova Gerty","Olímpico","Santa Maria"],
  'Suzano': ["Ipelândia","Jardim Brasil","Jardim Caxangá","Jardim Europa","Vila Fátima"]
};
